/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as LoginRegisterRouteImport } from './routes/_login/register'
import { Route as LoginLoginRouteImport } from './routes/_login/login'
import { Route as AppWorkScheduleRouteImport } from './routes/_app/work-schedule'
import { Route as AppLeaveRouteImport } from './routes/_app/leave'
import { Route as AppFormRequestRouteImport } from './routes/_app/form-request'
import { Route as AppEmployeeSetupRouteImport } from './routes/_app/employee-setup'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAttendancePolicyRouteImport } from './routes/_app/attendance-policy'
import { Route as AppAttendancePeriodRouteImport } from './routes/_app/attendance-period'
import { Route as AppHrFormsIndexRouteImport } from './routes/_app/hr-forms/index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees/index'
import { Route as AppEmployeesCreateRouteImport } from './routes/_app/employees/create'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees/$id'
import { Route as AppAttendanceSheetReportsRouteImport } from './routes/_app/attendance-sheet/reports'
import { Route as AppAdminUserRolesRouteImport } from './routes/_app/admin/user-roles'
import { Route as AppAdminUserManagementRouteImport } from './routes/_app/admin/user-management'
import { Route as AppAdminDesignationRouteImport } from './routes/_app/admin/designation'
import { Route as AppAdminDepartmentRouteImport } from './routes/_app/admin/department'
import { Route as AppAdminCompanyRouteImport } from './routes/_app/admin/company'
import { Route as AppAdminBranchRouteImport } from './routes/_app/admin/branch'
import { Route as AppAttendanceSheetIdIndexRouteImport } from './routes/_app/attendance-sheet/$id/index'
import { Route as AppAttendanceSheetIdSheetsEmpIdRouteImport } from './routes/_app/attendance-sheet/$id/sheets/$empId'
import { Route as AppAttendanceSheetViewerIdTimelogEmpidRouteImport } from './routes/_app/attendance-sheet/viewer/$id/timelog.$empid'

const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginRegisterRoute = LoginRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LoginRoute,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoginRoute,
} as any)
const AppWorkScheduleRoute = AppWorkScheduleRouteImport.update({
  id: '/work-schedule',
  path: '/work-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppFormRequestRoute = AppFormRequestRouteImport.update({
  id: '/form-request',
  path: '/form-request',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeSetupRoute = AppEmployeeSetupRouteImport.update({
  id: '/employee-setup',
  path: '/employee-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendancePolicyRoute = AppAttendancePolicyRouteImport.update({
  id: '/attendance-policy',
  path: '/attendance-policy',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendancePeriodRoute = AppAttendancePeriodRouteImport.update({
  id: '/attendance-period',
  path: '/attendance-period',
  getParentRoute: () => AppRoute,
} as any)
const AppHrFormsIndexRoute = AppHrFormsIndexRouteImport.update({
  id: '/hr-forms/',
  path: '/hr-forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesCreateRoute = AppEmployeesCreateRouteImport.update({
  id: '/employees/create',
  path: '/employees/create',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceSheetReportsRoute =
  AppAttendanceSheetReportsRouteImport.update({
    id: '/attendance-sheet/reports',
    path: '/attendance-sheet/reports',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUserRolesRoute = AppAdminUserRolesRouteImport.update({
  id: '/admin/user-roles',
  path: '/admin/user-roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserManagementRoute = AppAdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDesignationRoute = AppAdminDesignationRouteImport.update({
  id: '/admin/designation',
  path: '/admin/designation',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentRoute = AppAdminDepartmentRouteImport.update({
  id: '/admin/department',
  path: '/admin/department',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCompanyRoute = AppAdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBranchRoute = AppAdminBranchRouteImport.update({
  id: '/admin/branch',
  path: '/admin/branch',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceSheetIdIndexRoute =
  AppAttendanceSheetIdIndexRouteImport.update({
    id: '/attendance-sheet/$id/',
    path: '/attendance-sheet/$id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceSheetIdSheetsEmpIdRoute =
  AppAttendanceSheetIdSheetsEmpIdRouteImport.update({
    id: '/attendance-sheet/$id/sheets/$empId',
    path: '/attendance-sheet/$id/sheets/$empId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceSheetViewerIdTimelogEmpidRoute =
  AppAttendanceSheetViewerIdTimelogEmpidRouteImport.update({
    id: '/attendance-sheet/viewer/$id/timelog/$empid',
    path: '/attendance-sheet/viewer/$id/timelog/$empid',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/attendance-period': typeof AppAttendancePeriodRoute
  '/attendance-policy': typeof AppAttendancePolicyRoute
  '/calendar': typeof AppCalendarRoute
  '/employee-setup': typeof AppEmployeeSetupRoute
  '/form-request': typeof AppFormRequestRoute
  '/leave': typeof AppLeaveRoute
  '/work-schedule': typeof AppWorkScheduleRoute
  '/login': typeof LoginLoginRoute
  '/register': typeof LoginRegisterRoute
  '/admin/branch': typeof AppAdminBranchRoute
  '/admin/company': typeof AppAdminCompanyRoute
  '/admin/department': typeof AppAdminDepartmentRoute
  '/admin/designation': typeof AppAdminDesignationRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/admin/user-roles': typeof AppAdminUserRolesRoute
  '/attendance-sheet/reports': typeof AppAttendanceSheetReportsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/create': typeof AppEmployeesCreateRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/hr-forms/': typeof AppHrFormsIndexRoute
  '/attendance-sheet/$id/': typeof AppAttendanceSheetIdIndexRoute
  '/attendance-sheet/$id/sheets/$empId': typeof AppAttendanceSheetIdSheetsEmpIdRoute
  '/attendance-sheet/viewer/$id/timelog/$empid': typeof AppAttendanceSheetViewerIdTimelogEmpidRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/attendance-period': typeof AppAttendancePeriodRoute
  '/attendance-policy': typeof AppAttendancePolicyRoute
  '/calendar': typeof AppCalendarRoute
  '/employee-setup': typeof AppEmployeeSetupRoute
  '/form-request': typeof AppFormRequestRoute
  '/leave': typeof AppLeaveRoute
  '/work-schedule': typeof AppWorkScheduleRoute
  '/login': typeof LoginLoginRoute
  '/register': typeof LoginRegisterRoute
  '/admin/branch': typeof AppAdminBranchRoute
  '/admin/company': typeof AppAdminCompanyRoute
  '/admin/department': typeof AppAdminDepartmentRoute
  '/admin/designation': typeof AppAdminDesignationRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/admin/user-roles': typeof AppAdminUserRolesRoute
  '/attendance-sheet/reports': typeof AppAttendanceSheetReportsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/create': typeof AppEmployeesCreateRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/hr-forms': typeof AppHrFormsIndexRoute
  '/attendance-sheet/$id': typeof AppAttendanceSheetIdIndexRoute
  '/attendance-sheet/$id/sheets/$empId': typeof AppAttendanceSheetIdSheetsEmpIdRoute
  '/attendance-sheet/viewer/$id/timelog/$empid': typeof AppAttendanceSheetViewerIdTimelogEmpidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_login': typeof LoginRouteWithChildren
  '/_app/attendance-period': typeof AppAttendancePeriodRoute
  '/_app/attendance-policy': typeof AppAttendancePolicyRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/employee-setup': typeof AppEmployeeSetupRoute
  '/_app/form-request': typeof AppFormRequestRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/work-schedule': typeof AppWorkScheduleRoute
  '/_login/login': typeof LoginLoginRoute
  '/_login/register': typeof LoginRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/branch': typeof AppAdminBranchRoute
  '/_app/admin/company': typeof AppAdminCompanyRoute
  '/_app/admin/department': typeof AppAdminDepartmentRoute
  '/_app/admin/designation': typeof AppAdminDesignationRoute
  '/_app/admin/user-management': typeof AppAdminUserManagementRoute
  '/_app/admin/user-roles': typeof AppAdminUserRolesRoute
  '/_app/attendance-sheet/reports': typeof AppAttendanceSheetReportsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/employees/create': typeof AppEmployeesCreateRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/hr-forms/': typeof AppHrFormsIndexRoute
  '/_app/attendance-sheet/$id/': typeof AppAttendanceSheetIdIndexRoute
  '/_app/attendance-sheet/$id/sheets/$empId': typeof AppAttendanceSheetIdSheetsEmpIdRoute
  '/_app/attendance-sheet/viewer/$id/timelog/$empid': typeof AppAttendanceSheetViewerIdTimelogEmpidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance-period'
    | '/attendance-policy'
    | '/calendar'
    | '/employee-setup'
    | '/form-request'
    | '/leave'
    | '/work-schedule'
    | '/login'
    | '/register'
    | '/admin/branch'
    | '/admin/company'
    | '/admin/department'
    | '/admin/designation'
    | '/admin/user-management'
    | '/admin/user-roles'
    | '/attendance-sheet/reports'
    | '/employees/$id'
    | '/employees/create'
    | '/employees/'
    | '/hr-forms/'
    | '/attendance-sheet/$id/'
    | '/attendance-sheet/$id/sheets/$empId'
    | '/attendance-sheet/viewer/$id/timelog/$empid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance-period'
    | '/attendance-policy'
    | '/calendar'
    | '/employee-setup'
    | '/form-request'
    | '/leave'
    | '/work-schedule'
    | '/login'
    | '/register'
    | '/admin/branch'
    | '/admin/company'
    | '/admin/department'
    | '/admin/designation'
    | '/admin/user-management'
    | '/admin/user-roles'
    | '/attendance-sheet/reports'
    | '/employees/$id'
    | '/employees/create'
    | '/employees'
    | '/hr-forms'
    | '/attendance-sheet/$id'
    | '/attendance-sheet/$id/sheets/$empId'
    | '/attendance-sheet/viewer/$id/timelog/$empid'
  id:
    | '__root__'
    | '/_app'
    | '/_login'
    | '/_app/attendance-period'
    | '/_app/attendance-policy'
    | '/_app/calendar'
    | '/_app/employee-setup'
    | '/_app/form-request'
    | '/_app/leave'
    | '/_app/work-schedule'
    | '/_login/login'
    | '/_login/register'
    | '/_app/'
    | '/_app/admin/branch'
    | '/_app/admin/company'
    | '/_app/admin/department'
    | '/_app/admin/designation'
    | '/_app/admin/user-management'
    | '/_app/admin/user-roles'
    | '/_app/attendance-sheet/reports'
    | '/_app/employees/$id'
    | '/_app/employees/create'
    | '/_app/employees/'
    | '/_app/hr-forms/'
    | '/_app/attendance-sheet/$id/'
    | '/_app/attendance-sheet/$id/sheets/$empId'
    | '/_app/attendance-sheet/viewer/$id/timelog/$empid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_login/register': {
      id: '/_login/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LoginRegisterRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_app/work-schedule': {
      id: '/_app/work-schedule'
      path: '/work-schedule'
      fullPath: '/work-schedule'
      preLoaderRoute: typeof AppWorkScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form-request': {
      id: '/_app/form-request'
      path: '/form-request'
      fullPath: '/form-request'
      preLoaderRoute: typeof AppFormRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee-setup': {
      id: '/_app/employee-setup'
      path: '/employee-setup'
      fullPath: '/employee-setup'
      preLoaderRoute: typeof AppEmployeeSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-policy': {
      id: '/_app/attendance-policy'
      path: '/attendance-policy'
      fullPath: '/attendance-policy'
      preLoaderRoute: typeof AppAttendancePolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-period': {
      id: '/_app/attendance-period'
      path: '/attendance-period'
      fullPath: '/attendance-period'
      preLoaderRoute: typeof AppAttendancePeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr-forms/': {
      id: '/_app/hr-forms/'
      path: '/hr-forms'
      fullPath: '/hr-forms/'
      preLoaderRoute: typeof AppHrFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/create': {
      id: '/_app/employees/create'
      path: '/employees/create'
      fullPath: '/employees/create'
      preLoaderRoute: typeof AppEmployeesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-sheet/reports': {
      id: '/_app/attendance-sheet/reports'
      path: '/attendance-sheet/reports'
      fullPath: '/attendance-sheet/reports'
      preLoaderRoute: typeof AppAttendanceSheetReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-roles': {
      id: '/_app/admin/user-roles'
      path: '/admin/user-roles'
      fullPath: '/admin/user-roles'
      preLoaderRoute: typeof AppAdminUserRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/user-management': {
      id: '/_app/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AppAdminUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/designation': {
      id: '/_app/admin/designation'
      path: '/admin/designation'
      fullPath: '/admin/designation'
      preLoaderRoute: typeof AppAdminDesignationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/department': {
      id: '/_app/admin/department'
      path: '/admin/department'
      fullPath: '/admin/department'
      preLoaderRoute: typeof AppAdminDepartmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/company': {
      id: '/_app/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AppAdminCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/branch': {
      id: '/_app/admin/branch'
      path: '/admin/branch'
      fullPath: '/admin/branch'
      preLoaderRoute: typeof AppAdminBranchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-sheet/$id/': {
      id: '/_app/attendance-sheet/$id/'
      path: '/attendance-sheet/$id'
      fullPath: '/attendance-sheet/$id/'
      preLoaderRoute: typeof AppAttendanceSheetIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-sheet/$id/sheets/$empId': {
      id: '/_app/attendance-sheet/$id/sheets/$empId'
      path: '/attendance-sheet/$id/sheets/$empId'
      fullPath: '/attendance-sheet/$id/sheets/$empId'
      preLoaderRoute: typeof AppAttendanceSheetIdSheetsEmpIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-sheet/viewer/$id/timelog/$empid': {
      id: '/_app/attendance-sheet/viewer/$id/timelog/$empid'
      path: '/attendance-sheet/viewer/$id/timelog/$empid'
      fullPath: '/attendance-sheet/viewer/$id/timelog/$empid'
      preLoaderRoute: typeof AppAttendanceSheetViewerIdTimelogEmpidRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendancePeriodRoute: typeof AppAttendancePeriodRoute
  AppAttendancePolicyRoute: typeof AppAttendancePolicyRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppEmployeeSetupRoute: typeof AppEmployeeSetupRoute
  AppFormRequestRoute: typeof AppFormRequestRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppWorkScheduleRoute: typeof AppWorkScheduleRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminBranchRoute: typeof AppAdminBranchRoute
  AppAdminCompanyRoute: typeof AppAdminCompanyRoute
  AppAdminDepartmentRoute: typeof AppAdminDepartmentRoute
  AppAdminDesignationRoute: typeof AppAdminDesignationRoute
  AppAdminUserManagementRoute: typeof AppAdminUserManagementRoute
  AppAdminUserRolesRoute: typeof AppAdminUserRolesRoute
  AppAttendanceSheetReportsRoute: typeof AppAttendanceSheetReportsRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesCreateRoute: typeof AppEmployeesCreateRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppHrFormsIndexRoute: typeof AppHrFormsIndexRoute
  AppAttendanceSheetIdIndexRoute: typeof AppAttendanceSheetIdIndexRoute
  AppAttendanceSheetIdSheetsEmpIdRoute: typeof AppAttendanceSheetIdSheetsEmpIdRoute
  AppAttendanceSheetViewerIdTimelogEmpidRoute: typeof AppAttendanceSheetViewerIdTimelogEmpidRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendancePeriodRoute: AppAttendancePeriodRoute,
  AppAttendancePolicyRoute: AppAttendancePolicyRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppEmployeeSetupRoute: AppEmployeeSetupRoute,
  AppFormRequestRoute: AppFormRequestRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppWorkScheduleRoute: AppWorkScheduleRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminBranchRoute: AppAdminBranchRoute,
  AppAdminCompanyRoute: AppAdminCompanyRoute,
  AppAdminDepartmentRoute: AppAdminDepartmentRoute,
  AppAdminDesignationRoute: AppAdminDesignationRoute,
  AppAdminUserManagementRoute: AppAdminUserManagementRoute,
  AppAdminUserRolesRoute: AppAdminUserRolesRoute,
  AppAttendanceSheetReportsRoute: AppAttendanceSheetReportsRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesCreateRoute: AppEmployeesCreateRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppHrFormsIndexRoute: AppHrFormsIndexRoute,
  AppAttendanceSheetIdIndexRoute: AppAttendanceSheetIdIndexRoute,
  AppAttendanceSheetIdSheetsEmpIdRoute: AppAttendanceSheetIdSheetsEmpIdRoute,
  AppAttendanceSheetViewerIdTimelogEmpidRoute:
    AppAttendanceSheetViewerIdTimelogEmpidRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginLoginRoute: typeof LoginLoginRoute
  LoginRegisterRoute: typeof LoginRegisterRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLoginRoute: LoginLoginRoute,
  LoginRegisterRoute: LoginRegisterRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
