import { z } from 'zod'

export const employeeSchema = z.object({
  type: z.coerce.number(),
  prefix: z.string().optional(),
  firstName: z.string().min(2,"First Name is required"),
  middleName: z.string().min(2,"Middle Name is required"),
  lastName: z.string().min(2,"Lastname is required"),
  suffix: z.string().optional(),
  gender: z.coerce.number(),
  maritalStatus: z.coerce.number(),
  birthday: z.coerce.date(),
  religion: z.string().optional(),
  birthPlace: z.string().min(1,"Birthplace is required"),
  emaillAddress: z.string().optional(),
  phoneNumber: z.string().optional(),
  mobileNumber: z.string().optional(),
  nationality: z.string().min(1,"nationality is required"),
  region: z.string().optional(),
  bloodType: z.string().optional(),
  country: z.string().optional(),
  spouseName: z.string().optional(),
  spouseJobTitle: z.string().optional(),
  spouseCompany: z.string().optional(),
  spouseBirthday: z.coerce.date().optional(),
  sssNo: z.string().optional(),
  philHealthNo: z.string().optional(),
  tinNo: z.string().optional(),
  pagIbigNo: z.string().optional(),
  bankAccountNo: z.string().optional(),
  passportNo: z.string().optional(),
  passportExpiryDate: z.coerce.date().optional()
})

export type IEmployeeModel = z.infer<typeof employeeSchema>

export const employeeDefaultValues: IEmployeeModel = {
  type: 0,
  prefix: '',
  firstName: '',
  middleName: '',
  lastName: '',
  suffix: '',
  gender: 0,
  maritalStatus: 0,
  birthday: new Date(),
  religion: '',
  birthPlace: '',
  emaillAddress: '',
  phoneNumber: '',
  mobileNumber: '',
  nationality: '',
  region: '',
  bloodType: '',
  country: '',
  spouseName: '',
  spouseJobTitle: '',
  spouseCompany: '',
  spouseBirthday: undefined,
  sssNo: '',
  philHealthNo: '',
  tinNo: '',
  pagIbigNo: '',
  bankAccountNo: '',
  passportNo: '',
  passportExpiryDate: undefined,
}
